[[redirects]]
  from = "/*"
  to = "/error-pages/404/index.html"
  status = 404

[build]
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    Permissions-Policy = "sync-xhr=('self')"
    Expect-CT = "enforce, max-age=2592000"